# Generated by Django 2.2.4 on 2020-07-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaBonita', '0002_auto_20200715_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
