# Generated by Django 2.2.4 on 2020-07-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaBonita', '0003_productos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(upload_to='https://mariabonita.s3.us-east-2.amazonaws.com/media/mariabonita/'),
        ),
    ]
