# Generated by Django 2.2.4 on 2020-07-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MariaBonita', '0007_auto_20200731_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(storage='https://s3.us-east-2.amazonaws.com/media/mariabonita/', upload_to='mariabonita'),
        ),
    ]
